---
app_server_chiton_port: 80
app_server_chiton_port_https: 443
app_server_chiton_proxy_name: chiton-proxy
app_server_chiton_upstream_name: chiton-upstream
app_server_himation_limit_zone_name: himation-throttled
app_server_himation_port: 80
app_server_himation_port_https: 443
app_server_himation_proxy_name: himation-proxy
app_server_himation_upstream_name: himation-upstream
app_server_monit_config_chiton: "{{ monit_configs_dir }}/chiton.conf"
app_server_monit_config_himation: "{{ monit_configs_dir }}/himation.conf"
app_server_nginx_site_chiton: "{{ nginx_sites_dir }}/chiton.conf"
app_server_nginx_site_himation: "{{ nginx_sites_dir }}/himation.conf"

app_server_chiton_ssl_certificate_path: "{{ certbot_domains_dir }}/{{ app_server_chiton_server_name }}/{{ certbot_certificate_file_name }}"
app_server_chiton_ssl_chain_path: "{{ certbot_domains_dir }}/{{ app_server_chiton_server_name }}/{{ certbot_chain_file_name }}"
app_server_chiton_ssl_key_path: "{{ certbot_domains_dir }}/{{ app_server_chiton_server_name }}/{{ certbot_key_file_name }}"
app_server_himation_ssl_certificate_path: "{{ certbot_domains_dir }}/{{ app_server_himation_server_name }}/{{ certbot_certificate_file_name }}"
app_server_himation_ssl_chain_path: "{{ certbot_domains_dir }}/{{ app_server_himation_server_name }}/{{ certbot_chain_file_name }}"
app_server_himation_ssl_key_path: "{{ certbot_domains_dir }}/{{ app_server_himation_server_name }}/{{ certbot_key_file_name }}"
