---
chiton_admin_email: operations@coveryourbasics.com
chiton_admin_name: coveryourbasics
chiton_amazon_associates_tracking_id: coveryourbasics-staging-20
chiton_env_name: staging
chiton_log_dir: /var/log/chiton
chiton_run_dir: /var/run/chiton
