---
himation_allow_development: no
himation_app_server_port: 3000
himation_asset_server_port: 3001
himation_assets_path: /assets
himation_chiton_endpoint: null
himation_chiton_token: null
himation_current_version: null
himation_debug_assets: no
himation_deploy_ssh_key: "{{ vault__himation_deploy_ssh_key }}"
himation_deploy_ssh_key_public: "{{ vault__himation_deploy_ssh_key_public }}"
himation_git_ref: master
himation_group: himation
himation_group_id: null
himation_keep_releases: 10
himation_log_dir: null
himation_optimize_assets: no
himation_rollback_delta: 0
himation_root_dir: /var/cyb-himation
himation_run_dir: null
himation_server_name: null
himation_source_dir: "{{ himation_root_dir }}/source"
himation_use_debug_logging: no
himation_user: himation
himation_user_id: null
himation_user_authorized_keys: []
