---
himation_allow_development: no
himation_app_server_port: 3000
himation_asset_server_port: 3001
himation_assets_path: /assets
himation_chiton_endpoint: null
himation_chiton_token: null
himation_current_version: null
himation_daemonize: yes
himation_debug_assets: no
himation_deploy_ssh_key: null
himation_deploy_ssh_key_public: null
himation_environment: development
himation_git_ref: master
himation_group: himation
himation_group_id: null
himation_groups: []
himation_keep_releases: 10
himation_log_dir: null
himation_node_env: production
himation_optimize_assets: yes
himation_rollback_delta: 0
himation_root_dir: /var/cyb-himation
himation_run_dir: null
himation_sentry_dsn: null
himation_sentry_dsn_public: null
himation_server_name: null
himation_source_dir: "{{ himation_root_dir }}/source"
himation_track_errors: yes
himation_use_debug_logging: no
himation_user: himation
himation_user_authorized_keys: []
himation_user_id: null
