---
varnish_default_vcl: /etc/varnish/default.vcl
varnish_group: varnish
varnish_pidfile: /run/varnishd.pid
varnish_secret: /etc/varnish/secret

varnish_google_analytics_params:
  - cof
  - cx
  - gclid
  - ie
  - siteurl
  - utm_campaign
  - utm_content
  - utm_medium
  - utm_source

varnish_google_analytics_cookie_regexes:
  - __utm.
  - _ga
  - _gat
  - utmccn.
  - utmcmd.
  - utmctr
