---
chiton_activate_venv: no
chiton_admin_email: noreply@coveryourbasics.com
chiton_admin_name: chiton
chiton_admin_password: no
chiton_allow_tests: no
chiton_config_debug: no
chiton_config_secret_key: null
chiton_db_host: null
chiton_db_name: chiton
chiton_db_port: null
chiton_db_root_name: postgres
chiton_db_root_password: null
chiton_db_user_name: chiton
chiton_db_user_password: null
chiton_env_name: null
chiton_git_branch: master
chiton_group: chiton
chiton_group_id: null
chiton_server_address: null
chiton_server_address_local: 127.0.0.1
chiton_server_port: null
chiton_server_port_https: 443
chiton_server_port_local: 8080
chiton_server_upstream_name: chiton
chiton_ssl_certificate: null
chiton_ssl_certificate_path: null
chiton_ssl_certificate_key: null
chiton_ssl_certificate_key_path: null
chiton_source_dir: /var/cyb-chiton
chiton_use_https: false
chiton_user: chiton
chiton_user_authorized_keys: []
chiton_user_id: null
