---
chiton_activate_virtualenv: no
chiton_admin_email: noreply@coveryourbasics.com
chiton_admin_password: null
chiton_admin_username: chiton
chiton_allow_api_browsing: no
chiton_allow_development: no
chiton_allow_tests: no
chiton_api_user_name: null
chiton_api_user_token: null
chiton_amazon_associates_aws_access_key_id: null
chiton_amazon_associates_aws_secret_access_key: null
chiton_amazon_associates_tracking_id: null
chiton_backups_aws_access_key_id: null
chiton_backups_aws_secret_access_key: null
chiton_backups_local_retention_days: 30
chiton_backups_s3_bucket: null
chiton_assets_url: /assets/
chiton_config_debug: no
chiton_config_secret_key: null
chiton_current_version: null
chiton_daemonize: yes
chiton_default_email: noreply@coveryourbasics.com
chiton_deploy_ssh_key: null
chiton_deploy_ssh_key_public: null
chiton_db_host: null
chiton_db_port: null
chiton_db_root_name: null
chiton_db_root_password: null
chiton_db_user_password: null
chiton_environment: development
chiton_external_media_url: https://{{ chiton_server_name }}{{ chiton_media_url }}
chiton_git_ref: master
chiton_group: chiton
chiton_group_id: null
chiton_groups: []
chiton_gunicorn_log_level: info
chiton_gunicorn_threads: 1
chiton_gunicorn_workers: 1
chiton_keep_releases: 10
chiton_log_dir: null
chiton_log_level: INFO
chiton_media_url: /media/
chiton_pg_dump_path: pg_dump
chiton_pg_restore_path: pg_restore
chiton_pip_bin_name: pip
chiton_python_bin_name: python
chiton_redis_db: 0
chiton_rollback_delta: null
chiton_root_dir: /var/cyb-chiton
chiton_run_background_tasks: yes
chiton_run_dir: null
chiton_sentry_dsn: null
chiton_server_email: noreply@coveryourbasics.com
chiton_server_name: null
chiton_server_port: 4000
chiton_shopstyle_uid: null
chiton_stock_worker_count: 2
chiton_source_dir: "{{ chiton_root_dir }}/source"
chiton_track_errors: yes
chiton_user: chiton
chiton_user_authorized_keys: []
chiton_user_id: null
