---
chiton_activate_venv: no
chiton_admin_password: null
chiton_allow_tests: no
chiton_amazon_associates_aws_access_key_id: null
chiton_amazon_associates_aws_secret_access_key: null
chiton_amazon_associates_tracking_id: null
chiton_assets_dir: /var/cyb-chiton-assets
chiton_assets_url: /assets/
chiton_config_debug: no
chiton_config_secret_key: null
chiton_db_host: null
chiton_db_port: null
chiton_db_root_name: null
chiton_db_root_password: null
chiton_db_user_password: null
chiton_env_name: null
chiton_git_branch: master
chiton_group: chiton
chiton_group_id: null
chiton_server_address: 0.0.0.0
chiton_server_address_local: 127.0.0.1
chiton_server_port: null
chiton_server_port_https: 443
chiton_server_port_local: 8080
chiton_server_upstream_name: chiton
chiton_shopstyle_uid: null
chiton_source_dir: /var/cyb-chiton
chiton_ssl_certificate_key_path: null
chiton_ssl_certificate_path: null
chiton_use_https: false
chiton_user: chiton
chiton_user_authorized_keys: []
chiton_user_id: null
