---
- hosts: development:&app_servers
  roles:
    - role: app_server
    - role: nfs_server
    - role: vagrant
      vagrant_host_group: "{{ chiton_group }}"
      vagrant_host_user: "{{ chiton_user }}"
    - role: firewall
      firewall_ports:
        - port: "{{ nfs_server_lockd_port }}"
          protocol: any
        - port: "{{ nfs_server_mountd_port }}"
          protocol: any
        - port: "{{ nfs_server_nfs_port }}"
          protocol: any
        - port: "{{ nfs_server_portmap_port }}"
          protocol: any
        - port: "{{ nfs_server_statd_port }}"
          protocol: any
        - port: "{{ nfs_server_statd_outgoing_port }}"
          protocol: any
