---
- hosts: development-chiton.coveryourbasics.com
  roles:
    - role: common
    - role: docker
    - role: postgresql_server
      postgresql_server_address: "{{ chiton_db_host }}"
      postgresql_server_port: "{{ chiton_db_port }}"
      postgresql_server_root_password: "{{ chiton_db_root_password }}"
      postgresql_server_use_docker: yes
      postgresql_server_version: "{{ chiton_postgresql_server_version }}"
    - role: chiton
      chiton_activate_venv: yes
      chiton_config_debug: yes
      chiton_env_name: development
    - role: vagrant
