---
- name: install Docker dependencies
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - apt-transport-https
    - ca-certificates
    - "linux-image-extra-{{ ansible_kernel }}"

- name: add the Docker package repository's key
  apt_key:
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D
    state: present

- name: add the Docker package repository
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release }} main
    state: present

- name: install Docker
  apt:
    name: docker-engine
    state: latest

- name: install the Python docker module
  pip:
    name: docker-py
    version: "{{ docker_docker_py_version }}"
    state: present
