---
chiton_allow_tests: yes
chiton_aws_advertising_associate_tag: covyoubas-dev-20
chiton_db_host: 127.0.0.1
chiton_db_port: 5432
chiton_db_root_name: postgres
chiton_group: chiton
chiton_group_id: 3000
chiton_server_address: 10.10.10.20
chiton_server_port: 80
chiton_server_port_https: 443
chiton_source_dir: /var/cyb-chiton
chiton_use_https: true
chiton_user: chiton
chiton_user_authorized_keys:
  - "{{ lookup('file', lookup('env', 'CYB_VAGRANT_KEY_PUBLIC')) }}"
chiton_user_id: 3000
postgresql_server_data_dir: /var/cyb-chiton-data
vagrant_host_group: chiton
vagrant_host_home_dir: /vagrant-host-home
vagrant_host_user: chiton
