---
himation_nodejs_version: 4.2.4
himation_pm2_version: 1.1.3
himation_user_custom_profile: "{{ himation_user_home_dir }}/.profile.himation"
himation_user_home_dir: "/home/{{ himation_user }}"
himation_user_shell: /bin/bash
himation_user_ssh_dir: "{{ himation_user_home_dir }}/.ssh"

himation_assets_dir_name: assets
himation_public_dir_name: public
himation_source_dir_name: source

himation_current_dir: "{{ himation_root_dir }}/current"
himation_config_dir: "{{ himation_root_dir }}/config"
himation_scripts_dir: "{{ himation_root_dir }}/scripts"
himation_versions_dir: "{{ himation_root_dir }}/versions"

himation_log_dir: /var/log/himation
himation_run_dir: /var/run/himation

himation_app_log_path: "{{ himation_log_dir_final }}/app.log"
himation_assets_dir: "{{ himation_current_dir }}/{{ himation_assets_dir_name }}"
himation_config_file: "{{ himation_config_dir }}/settings.json"
himation_current_source_dir: "{{ himation_current_dir }}/{{ himation_source_dir_name }}"
himation_pm2_app_definition: "{{ himation_config_dir }}/application.yml"
himation_pm2_app_name: himation
himation_pm2_pidfile: "{{ himation_run_dir }}/pm2.pid"
himation_public_dir: "{{ himation_current_dir }}/{{ himation_public_dir_name }}"
