---
- name: create the Docker container
  docker:
    name: cyb-postgres
    image: postgres:{{ postgres_server_version }}
    pull: always
    ports: "{{ postgres_server_port }}:5432"
    env:
      POSTGRES_PASSWORD: "{{ postgres_server_root_password }}"
      POSTGRES_USER: "{{ postgres_server_root_user }}"
    state: reloaded
